imports:
    - { resource: tasks.phpcsfixer2.config.yml }

parameters:
    git_dir: .
    bin_dir: vendor/bin
    process_timeout: 180

    ascii:
        failed: ~
        succeeded: ~

    extensions:
        - Wearejust\GrumPHPExtra\Extension\Loader
        - drupol\PhpConventions\GrumphpTasksExtension

    # PHP CS
    tasks.phpcs.standard: PSR12
    tasks.phpcs.ignore_patterns:
        - vendor/
        - spec/
    tasks.phpcs.triggered_by:
        - php

    # PHP Infection
    tasks.infection.min_covered_msi: 80
    tasks.infection.min_msi: 80
    tasks.infection.threads: 10

    # PHP Stan
    tasks.phpstan.ignore_patterns:
        - '/spec/'
        - '/benchmarks/'
    tasks.phpstan.level: 7

    # PHP CS Fixer
    tasks.phpcsfixer2.triggered_by:
        - php

    # Tasks.
    tasks:
        # Composer checks
        composer:
            metadata:
                priority: 6300

        # Composer Normalize
        composer_normalize:
            metadata:
                priority: 6200

        # YAML Lint
        yamllint:
            whitelist_patterns: []
            ignore_patterns: []
            object_support: true
            exception_on_invalid_type: true
            parse_constant: true
            parse_custom_tags: true
            metadata:
                priority: 5200

        # JSON Lint
        jsonlint:
            ignore_patterns: []
            detect_key_conflicts: true
            metadata:
                priority: 5100

        # PHP Lint
        phplint:
            metadata:
                priority: 4400

        # PHP CS Fixer (autofix)
        php_cs_auto_fixerv2:
            config: '%tasks.phpcsfixer2.config%'
            config_contains_finder: true
            triggered_by: '%tasks.phpcsfixer2.triggered_by%'
            verbose: true
            allow_risky: true
            using_cache: false
            metadata:
                priority: 4350

        # PHP CS Fixer
        phpcsfixer2:
            config: '%tasks.phpcsfixer2.config%'
            config_contains_finder: true
            triggered_by: '%tasks.phpcsfixer2.triggered_by%'
            verbose: true
            allow_risky: true
            using_cache: false
            metadata:
                priority: 4300

        # PHP CS
        phpcs:
            standard: '%tasks.phpcs.standard%'
            ignore_patterns: '%tasks.phpcs.ignore_patterns%'
            triggered_by: '%tasks.phpcs.triggered_by%'
            metadata:
                priority: 4200

        # PHP Stan
        phpstan:
            autoload_file: ~
            configuration: ~
            level: '%tasks.phpstan.level%'
            force_patterns: []
            ignore_patterns: '%tasks.phpstan.ignore_patterns%'
            triggered_by: ['php']
            metadata:
                priority: 3300
