imports:
  - { resource: tasks.phpcsfixer2.config.yml }
  - { resource: tasks.phpcsfixer2.rules.yml }

parameters:
  git_dir: .
  bin_dir: vendor/bin
  process_timeout: 180

  ascii:
    failed: ~
    succeeded: ~

  # PHP CS
  tasks.phpcs.standard: PSR2
  tasks.phpcs.ignore_patterns:
    - vendor/
    - spec/
  tasks.phpcs.triggered_by:
    - php

  # PHP Infection
  tasks.infection.min_covered_msi: 80
  tasks.infection.min_msi: 80
  tasks.infection.threads: 10

  # PHP Stan
  tasks.phpstan.ignore_patterns:
    - '/spec/'
    - '/benchmarks/'

  # PHP CPD
  tasks.phpcpd.directory: './src'

  # Tasks.
  tasks:
    # Composer checks
    composer:
      metadata:
        priority: 6200

    # Security checks
    securitychecker:
      lockfile: ./composer.lock
      format: ~
      end_point: ~
      timeout: ~
      run_always: false
      metadata:
        priority: 6100

    # YAML Lint
    yamllint:
      whitelist_patterns: []
      ignore_patterns: []
      object_support: true
      exception_on_invalid_type: true
      parse_constant: true
      parse_custom_tags: true
      metadata:
        priority: 5200

    # JSON Lint
    jsonlint:
      ignore_patterns: []
      detect_key_conflicts: true
      metadata:
        priority: 5100

    # PHP Lint
    phplint:
      metadata:
        priority: 4400

    # PHP CS Fixer
    phpcsfixer2:
      config: '%tasks.phpcsfixer2.config%'
      rules: '%tasks.phpcsfixer2.rules%'
      config_contains_finder: true
      verbose: true
      allow_risky: true
      using_cache: false
      metadata:
        priority: 4300

    # PHP CS
    phpcs:
      standard: '%tasks.phpcs.standard%'
      ignore_patterns: '%tasks.phpcs.ignore_patterns%'
      triggered_by: '%tasks.phpcs.triggered_by%'
      metadata:
        priority: 4200

    # PHP Copy Paste Detector
    phpcpd:
      directory: '%tasks.phpcpd.directory%'
      metadata:
        priority: 4100

    # PHP Stan
    phpstan:
      autoload_file: ~
      configuration: ~
      level: 7
      force_patterns: []
      ignore_patterns: '%tasks.phpstan.ignore_patterns%'
      triggered_by: ['php']
      metadata:
        priority: 3300

    # PHP Spec
    phpspec:
      format: pretty
      stop_on_failure: true
      verbose: true
      metadata:
        priority: 3200

    # PHP Infection
    infection:
      threads: '%tasks.infection.threads%'
      min_msi: '%tasks.infection.min_msi%'
      min_covered_msi: '%tasks.infection.min_covered_msi%'
      metadata:
        priority: 3100
