parameters:
  git_dir: .
  bin_dir: vendor/bin
  process_timeout: 180

  ascii:
    failed: ~
    succeeded: ~

  # PHP CS
  tasks.phpcs.standard: PSR2
  tasks.phpcs.ignore_patterns:
    - vendor/
    - spec/
  tasks.phpcs.triggered_by:
    - php

  # PHP Infection
  tasks.infection.min_covered_msi: 80
  tasks.infection.min_msi: 80
  tasks.infection.threads: 10

  # PHP Stan
  tasks.phpstan.ignore_patterns:
    - '/spec/'
    - '/benchmarks/'

  # PHP CPD
  tasks.phpcpd.directory: './src'

  # PHP CS Fixer parameters
  tasks.phpcsfixer2.config: ./vendor/drupol/php-conventions/config/php_cs_fixer.config.php
  tasks.phpcsfixer2.rules:
    '@PSR2': true
    '@PhpCsFixer': true
    '@PhpCsFixer:risky' : true
    blank_line_before_statement:
      statements:
        - break
        - continue
        - declare
        - return
        - throw
        - try
    cast_spaces:
      space: single
    class_definition:
      multi_line_extends_each_single_line: true
    concat_space:
      spacing: one
    declare_equal_normalize:
      space: single
    declare_strict_types: true
    is_null: true
    multiline_whitespace_before_semicolons:
      strategy: no_multi_line
    native_function_invocation:
      include: '@all'
    no_extra_blank_lines:
      tokens:
        - extra
        - curly_brace_block
        - parenthesis_brace_block
        - square_brace_block
        - return
        - throw
        - use
        - use_trait
    ordered_class_elements:
      order:
        - use_trait
        - constant_public
        - constant_protected
        - constant_private
        - property_public
        - property_protected
        - property_private
        - construct
        - destruct
        - magic
        - phpunit
        - method_public
        - method_protected
        - method_private
      sortAlgorithm: alpha
    phpdoc_align: false
    self_accessor: false
    yoda_style:
      equal: true
      identical: true
      less_and_greater: true
      always_move_variable: true

  # Tasks.
  tasks:
    # Commit message format.
    git_commit_message:
      matchers:
        - '/^([A-Z]+\-\d+|Issue #\d+): [A-Z].+\./'
      case_insensitive: false
      enforce_no_subject_trailing_period: false
      multiline: false
      max_body_width: 0
      max_subject_width: 0

    # PHP CS Fixer
    phpcsfixer2:
      config: '%tasks.phpcsfixer2.config%'
      rules: '%tasks.phpcsfixer2.rules%'
      config_contains_finder: true
      verbose: true
      allow_risky: true
      using_cache: false

    composer: ~

    phpcpd:
      directory: '%tasks.phpcpd.directory%'

    phpstan:
      autoload_file: ~
      configuration: ~
      level: 7
      force_patterns: []
      ignore_patterns: '%tasks.phpstan.ignore_patterns%'
      triggered_by: ['php']

    phpspec:
      format: pretty
      stop_on_failure: true
      verbose: true

    securitychecker:
      lockfile: ./composer.lock
      format: ~
      end_point: ~
      timeout: ~
      run_always: false

    infection:
      threads: '%tasks.infection.threads%'
      min_msi: '%tasks.infection.min_msi%'
      min_covered_msi: '%tasks.infection.min_covered_msi%'

    phpcs:
      standard: '%tasks.phpcs.standard%'
      ignore_patterns: '%tasks.phpcs.ignore_patterns%'
      triggered_by: '%tasks.phpcs.triggered_by%'

    yamllint:
      whitelist_patterns: []
      ignore_patterns: []
      object_support: true
      exception_on_invalid_type: true
      parse_constant: true
      parse_custom_tags: true

    jsonlint:
      ignore_patterns: []
      detect_key_conflicts: true
