imports:
    - { resource: tasks.phpcsfixer2.config.yml }

parameters:
    # PHP CS
    tasks.phpcs.standard: PSR12
    tasks.phpcs.ignore_patterns:
        - "/benchmarks/"
        - "/spec/"
        - "/tests/"
        - "/vendor/"
    tasks.phpcs.triggered_by:
        - php

    # PHP Infection
    tasks.infection.min_covered_msi: 80
    tasks.infection.min_msi: 80
    tasks.infection.threads: 10

    # PHP Stan
    tasks.phpstan.autoload_file: ~
    tasks.phpstan.configuration: ~
    tasks.phpstan.ignore_patterns:
        - "/benchmarks/"
        - "/spec/"
        - "/tests/"
        - "/vendor/"
    tasks.phpstan.level: max
    tasks.phpstan.triggered_by:
        - php
    tasks.phpstan.force_patterns: []
    tasks.phpstan.blocking: false

    # PHP CS Fixer
    tasks.phpcsfixer2.config_contains_finder: true
    tasks.phpcsfixer2.triggered_by:
        - php

    # Twigcs
    tasks.twigcs.path: src
    tasks.twigcs.triggered_by: ['twig']
    tasks.twigcs.ruleset: 'Allocine\Twigcs\Ruleset\Official'
    tasks.twigcs.severity: 'error'

    # Security Checker
    tasks.securitychecker.format: ~
    tasks.securitychecker.end_point: ~
    tasks.securitychecker.timeout: ~
    tasks.securitychecker.lockfile: ./composer.lock

grumphp:
    process_timeout: null
    parallel:
        enabled: false
        max_workers: 32
    fixer:
        enabled: true
        fix_by_default: true

    extensions:
        - drupol\PhpConventions\GrumphpTasksExtension

    # Testsuites
    testsuites:
        cs:
            tasks:
                - composer
                - composer_normalize
                - yamllint
                - phplint
                - twigcs
                - phpcsfixer
                - phpcs

        static-analysis:
            tasks:
                - phpstan

        security:
            tasks:
                - securitychecker

    # Tasks.
    tasks:
        # Security Checker
        securitychecker:
            lockfile: '%tasks.securitychecker.lockfile%'
            format: '%tasks.securitychecker.format%'
            end_point: '%tasks.securitychecker.end_point%'
            timeout: '%tasks.securitychecker.timeout%'
            run_always: false

        # Composer checks
        composer: ~

        # Composer Normalize
        composer_normalize: ~

        # YAML Lint
        yamllint:
            whitelist_patterns: []
            ignore_patterns: []
            object_support: true
            exception_on_invalid_type: true
            parse_constant: true
            parse_custom_tags: true

        # JSON Lint
        jsonlint:
            ignore_patterns: []
            detect_key_conflicts: true

        # PHP Lint
        phplint: ~

        # Twig CS
        twigcs:
            path: '%tasks.twigcs.path%'
            ruleset: '%tasks.twigcs.ruleset%'
            severity: '%tasks.twigcs.severity%'
            triggered_by: '%tasks.twigcs.triggered_by%'

        # PHP CS Fixer
        phpcsfixer:
            config: '%tasks.phpcsfixer2.config%'
            config_contains_finder: true
            triggered_by: '%tasks.phpcsfixer2.triggered_by%'
            verbose: true
            allow_risky: true
            using_cache: false

        # PHP CS
        phpcs:
            standard: '%tasks.phpcs.standard%'
            ignore_patterns: '%tasks.phpcs.ignore_patterns%'
            triggered_by: '%tasks.phpcs.triggered_by%'

        # PHP Stan
        phpstan:
            autoload_file: '%tasks.phpstan.autoload_file%'
            configuration: '%tasks.phpstan.configuration%'
            level: '%tasks.phpstan.level%'
            force_patterns: '%tasks.phpstan.force_patterns%'
            ignore_patterns: '%tasks.phpstan.ignore_patterns%'
            triggered_by: '%tasks.phpstan.triggered_by%'
            metadata:
                blocking: '%tasks.phpstan.blocking%'
